### ISSUE TITLE
Use custom endpoints when released

### ISSUE THREAD

**Issue by bdunogier** [bdunogier/ezplatform-graphql-bundle#1]
In `dev-master` of the OverBlog bundle, multiple endpoints can be configured:

```
overblog_graphql:
    definitions:
        schema:
            ezp:
                query: Query
                mutation: Mutation
```

The endpoints are then at `/graphql/ezp` and `/graphiql/ezp`. This would greatly enhance extensibility.
