### ISSUE TITLE
Add CORS headers to allow GraphQL access domains

### ISSUE THREAD

**Issue by janit** [bdunogier/ezplatform-graphql-bundle#24]
Browsers can't make requests to the GraphQL API across different domains because of security reasons. To bypass this we need to send the proper [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). This can be either implemented as a part of the bundle or documented.

For example, using the [NelmioCORSBundle](https://github.com/nelmio/NelmioCorsBundle) following configuration works on [react.nu](https://react.nu):

```
nelmio_cors:
    paths:
        '^/graphql/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
```
